[toolchain]
channel = "1.90.0"
components = ["clippy"]

# Bumping MSRV
# * update `toolchain.channel` key in `rust-toolchain.toml` (this file)
# * update `book/src/guide/requirements.md`
# * update `workspace.package.rust-version` key in root `Cargo.toml`
