[package]
name = "ragu_acceleration"
version.workspace = true
authors.workspace = true
description = "Hardware acceleration for the Ragu project"
license.workspace = true
edition.workspace = true
rust-version.workspace = true

readme = "README.md"
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.rs/ragu_acceleration"
categories = ["cryptography", "mathematics", "algorithms", "development-tools", "no-std"]
keywords = ["cryptography", "zero-knowledge", "acceleration", "circuits", "pcd"]

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "katex-header.html"]

[features]
default = []
multicore = ["ragu_backend/multicore", "std"]
std = []

[lib]
bench = false

[dependencies]
ragu_backend = { path = "../ragu_backend", version = "0.0.0", default-features = false }

[dev-dependencies]
proptest = { workspace = true }
ragu_arithmetic = { path = "../ragu_arithmetic", version = "0.0.0", default-features = false, features = ["alloc"] }
ragu_circuits = { path = "../ragu_circuits", version = "0.0.0", default-features = false, features = ["alloc"] }
ragu_core = { path = "../ragu_core", version = "0.0.0", default-features = false, features = ["alloc"] }
ragu_primitives = { path = "../ragu_primitives", version = "0.0.0", default-features = false, features = ["alloc"] }
ragu_testing = { path = "../ragu_testing", version = "0.0.0", default-features = false }
