[package]
name = "ragu_backend"
version.workspace = true
authors.workspace = true
description = "Backend for the Ragu project"
license.workspace = true
edition.workspace = true
rust-version.workspace = true

readme = "README.md"
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.rs/ragu_backend"
categories = ["cryptography", "mathematics", "algorithms", "development-tools", "no-std"]
keywords = ["cryptography", "zero-knowledge", "backend", "circuits", "pcd"]

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "katex-header.html"]

[features]
default = []
multicore = ["ragu_arithmetic/multicore", "ragu_circuits/multicore", "std"]
std = []

[lib]
bench = false

[dependencies]
ragu_arithmetic = { path = "../ragu_arithmetic", version = "0.0.0", default-features = false, features = ["alloc"] }
ragu_circuits = { path = "../ragu_circuits", version = "0.0.0", default-features = false, features = ["alloc"] }
