import Ragu.Instances.Point.AllocFp
import Ragu.Instances.Point.AllocFq
import Ragu.Instances.Point.Double
import Ragu.Instances.Point.DoubleAndAddIncomplete
import Ragu.Instances.Point.AddIncomplete
import Ragu.Instances.Point.ConditionalEndo
import Ragu.Instances.Point.ConditionalNegate
import Ragu.Instances.Point.ConsistentFp
import Ragu.Instances.Point.ConsistentFq
import Ragu.Instances.Element.Mul
import Ragu.Instances.Element.Square
import Ragu.Instances.Element.Alloc
import Ragu.Instances.Element.AllocSquare
import Ragu.Instances.Element.DivNonzero
import Ragu.Instances.Element.FoldN2
import Ragu.Instances.Element.FoldN3
import Ragu.Instances.Element.FoldN7
import Ragu.Instances.Element.FoldN19
import Ragu.Instances.Element.EnforceRootOfUnityK2
import Ragu.Instances.Element.EnforceRootOfUnityK5
import Ragu.Instances.Element.EnforceZero
import Ragu.Instances.Element.EnforceInvertible
import Ragu.Instances.Element.Invertible
import Ragu.Instances.Element.InvertibleConsistent
import Ragu.Instances.Element.Invert
import Ragu.Instances.Element.InvertWith
import Ragu.Instances.Element.EnforceNonzero
import Ragu.Instances.NonzeroBank.ScopeK0
import Ragu.Instances.NonzeroBank.ScopeK1
import Ragu.Instances.NonzeroBank.ScopeK2
import Ragu.Instances.Element.IsEqual
import Ragu.Instances.Element.IsZero
import Ragu.Instances.Core.Mul
import Ragu.Instances.Boolean.Alloc
import Ragu.Instances.Boolean.And
import Ragu.Instances.Boolean.ConditionalSelect
import Ragu.Instances.Boolean.Consistent
import Ragu.Instances.Boolean.ConditionalEnforceEqual
import Ragu.Instances.Endoscalar.Alloc
import Ragu.Instances.Endoscalar.Extract
import Ragu.Instances.Endoscalar.GroupScale
import Ragu.Instances.Endoscalar.Lift
import Ragu.Instances.Endoscalar.HoistedAlloc
import Ragu.Instances.Endoscalar.HoistedGroupScale
import Ragu.Instances.Endoscalar.HoistedLift
import Ragu.Instances.Endoscalar.EnforceProducts
import Ragu.Instances.Horner.N3
import Ragu.Instances.Horner.N7
import Ragu.Instances.Horner.N19
import Ragu.Instances.Horner.KyN3
import Ragu.Instances.Poseidon.Hash1Fp
import Ragu.Instances.Poseidon.Hash4Fp
import Ragu.Instances.Poseidon.Hash1Fq
import Ragu.Instances.Poseidon.Blocks2Squeeze3Fp
import Ragu.Instances.Poseidon.Hash1SaveResumeFp
import Ragu.Instances.Poseidon.InterleavedFp
import Ragu.Instances.Poseidon.Blocks1Tail2Squeeze2Fp
