import Ragu.Fingerprint
import Ragu.Instances

namespace Ragu.Fingerprint

/-- Every exported circuit instance, paired with its Lean module name.

Autogenerated by `lean_extraction`; do not edit. Used by the exact and
randomized fingerprint executables, whose outputs CI compares against
the corresponding Rust evaluators. -/
def instances : List (String × Ragu.Core.Statements.FormalInstance) := [
  ("Ragu.Instances.Point.AllocFp", Ragu.Instances.Point.AllocFp.formal_instance),
  ("Ragu.Instances.Point.AllocFq", Ragu.Instances.Point.AllocFq.formal_instance),
  ("Ragu.Instances.Point.Double", Ragu.Instances.Point.Double.formal_instance),
  ("Ragu.Instances.Point.DoubleAndAddIncomplete", Ragu.Instances.Point.DoubleAndAddIncomplete.formal_instance),
  ("Ragu.Instances.Point.AddIncomplete", Ragu.Instances.Point.AddIncomplete.formal_instance),
  ("Ragu.Instances.Point.ConditionalEndo", Ragu.Instances.Point.ConditionalEndo.formal_instance),
  ("Ragu.Instances.Point.ConditionalNegate", Ragu.Instances.Point.ConditionalNegate.formal_instance),
  ("Ragu.Instances.Point.ConsistentFp", Ragu.Instances.Point.ConsistentFp.formal_instance),
  ("Ragu.Instances.Point.ConsistentFq", Ragu.Instances.Point.ConsistentFq.formal_instance),
  ("Ragu.Instances.Element.Mul", Ragu.Instances.Element.Mul.formal_instance),
  ("Ragu.Instances.Element.Square", Ragu.Instances.Element.Square.formal_instance),
  ("Ragu.Instances.Element.Alloc", Ragu.Instances.Element.Alloc.formal_instance),
  ("Ragu.Instances.Element.AllocSquare", Ragu.Instances.Element.AllocSquare.formal_instance),
  ("Ragu.Instances.Element.DivNonzero", Ragu.Instances.Element.DivNonzero.formal_instance),
  ("Ragu.Instances.Element.FoldN2", Ragu.Instances.Element.FoldN2.formal_instance),
  ("Ragu.Instances.Element.FoldN3", Ragu.Instances.Element.FoldN3.formal_instance),
  ("Ragu.Instances.Element.FoldN7", Ragu.Instances.Element.FoldN7.formal_instance),
  ("Ragu.Instances.Element.FoldN19", Ragu.Instances.Element.FoldN19.formal_instance),
  ("Ragu.Instances.Element.EnforceRootOfUnityK2", Ragu.Instances.Element.EnforceRootOfUnityK2.formal_instance),
  ("Ragu.Instances.Element.EnforceRootOfUnityK5", Ragu.Instances.Element.EnforceRootOfUnityK5.formal_instance),
  ("Ragu.Instances.Element.EnforceZero", Ragu.Instances.Element.EnforceZero.formal_instance),
  ("Ragu.Instances.Element.EnforceInvertible", Ragu.Instances.Element.EnforceInvertible.formal_instance),
  ("Ragu.Instances.Element.Invertible", Ragu.Instances.Element.Invertible.formal_instance),
  ("Ragu.Instances.Element.InvertibleConsistent", Ragu.Instances.Element.InvertibleConsistent.formal_instance),
  ("Ragu.Instances.Element.Invert", Ragu.Instances.Element.Invert.formal_instance),
  ("Ragu.Instances.Element.InvertWith", Ragu.Instances.Element.InvertWith.formal_instance),
  ("Ragu.Instances.Element.EnforceNonzero", Ragu.Instances.Element.EnforceNonzero.formal_instance),
  ("Ragu.Instances.NonzeroBank.ScopeK0", Ragu.Instances.NonzeroBank.ScopeK0.formal_instance),
  ("Ragu.Instances.NonzeroBank.ScopeK1", Ragu.Instances.NonzeroBank.ScopeK1.formal_instance),
  ("Ragu.Instances.NonzeroBank.ScopeK2", Ragu.Instances.NonzeroBank.ScopeK2.formal_instance),
  ("Ragu.Instances.Element.IsEqual", Ragu.Instances.Element.IsEqual.formal_instance),
  ("Ragu.Instances.Element.IsZero", Ragu.Instances.Element.IsZero.formal_instance),
  ("Ragu.Instances.Core.Mul", Ragu.Instances.Core.Mul.formal_instance),
  ("Ragu.Instances.Boolean.Alloc", Ragu.Instances.Boolean.Alloc.formal_instance),
  ("Ragu.Instances.Boolean.And", Ragu.Instances.Boolean.And.formal_instance),
  ("Ragu.Instances.Boolean.ConditionalSelect", Ragu.Instances.Boolean.ConditionalSelect.formal_instance),
  ("Ragu.Instances.Boolean.Consistent", Ragu.Instances.Boolean.Consistent.formal_instance),
  ("Ragu.Instances.Boolean.ConditionalEnforceEqual", Ragu.Instances.Boolean.ConditionalEnforceEqual.formal_instance),
  ("Ragu.Instances.Endoscalar.Alloc", Ragu.Instances.Endoscalar.Alloc.formal_instance),
  ("Ragu.Instances.Endoscalar.Extract", Ragu.Instances.Endoscalar.Extract.formal_instance),
  ("Ragu.Instances.Endoscalar.GroupScale", Ragu.Instances.Endoscalar.GroupScale.formal_instance),
  ("Ragu.Instances.Endoscalar.Lift", Ragu.Instances.Endoscalar.Lift.formal_instance),
  ("Ragu.Instances.Endoscalar.HoistedAlloc", Ragu.Instances.Endoscalar.HoistedAlloc.formal_instance),
  ("Ragu.Instances.Endoscalar.HoistedGroupScale", Ragu.Instances.Endoscalar.HoistedGroupScale.formal_instance),
  ("Ragu.Instances.Endoscalar.HoistedLift", Ragu.Instances.Endoscalar.HoistedLift.formal_instance),
  ("Ragu.Instances.Endoscalar.EnforceProducts", Ragu.Instances.Endoscalar.EnforceProducts.formal_instance),
  ("Ragu.Instances.Horner.N3", Ragu.Instances.Horner.N3.formal_instance),
  ("Ragu.Instances.Horner.N7", Ragu.Instances.Horner.N7.formal_instance),
  ("Ragu.Instances.Horner.N19", Ragu.Instances.Horner.N19.formal_instance),
  ("Ragu.Instances.Horner.KyN3", Ragu.Instances.Horner.KyN3.formal_instance),
  ("Ragu.Instances.Poseidon.Hash1Fp", Ragu.Instances.Poseidon.Hash1Fp.formal_instance),
  ("Ragu.Instances.Poseidon.Hash4Fp", Ragu.Instances.Poseidon.Hash4Fp.formal_instance),
  ("Ragu.Instances.Poseidon.Hash1Fq", Ragu.Instances.Poseidon.Hash1Fq.formal_instance),
  ("Ragu.Instances.Poseidon.Blocks2Squeeze3Fp", Ragu.Instances.Poseidon.Blocks2Squeeze3Fp.formal_instance),
  ("Ragu.Instances.Poseidon.Hash1SaveResumeFp", Ragu.Instances.Poseidon.Hash1SaveResumeFp.formal_instance),
  ("Ragu.Instances.Poseidon.InterleavedFp", Ragu.Instances.Poseidon.InterleavedFp.formal_instance),
  ("Ragu.Instances.Poseidon.Blocks1Tail2Squeeze2Fp", Ragu.Instances.Poseidon.Blocks1Tail2Squeeze2Fp.formal_instance)
]

end Ragu.Fingerprint
